import { Colors } from "./Colors";

const Data = [

    {
        id: 1,
        title: "Don't smoke",
        content: "Don't smoke",
        time: "6:00 am - 10:00 am",
        foregroundColor: Colors.smokeColor,
        habitImage: require('../../assets/images/Smoking.png'),
        plantImage: require('../../assets/images/planet.png'),
        flowerImage: require('../../assets/images/flower-pot 1.png'),
        exportImage: require('../../assets/images/Export%.png'),
        backImage: require('../../assets/background/blue.png'),
        backImageSize: { width: 90, height: 73 },
        cardColor: Colors.smokeBlue,
        buttonText: "Health",
        buttonColor: Colors.textSmoke,
    },
    {
        id: 2,
        title: "Glass of Water",
        content: "Drink 10 cups Water",
        time: "6:00 am - 6:00 pm",
        foregroundColor: Colors.waterColer,
        habitImage: require('../../assets/images/Bottle of water.png'),
        plantImage: require('../../assets/images/planet.png'),
        flowerImage: require('../../assets/images/flower-pot 1.png'),
        exportImage: require('../../assets/images/Export%.png'),
        backImage: require('../../assets/background/violet.png'),
        backImageSize: { width: 74.7, height: 78.93 },
        cardColor: Colors.waterPurple,
        buttonText: "Health",
        buttonColor: Colors.textWater,
    },
    {
        id: 3,
        title: "Get outside",
        content: "Get outside",
        time: "6:00 am - 6:00 pm",
        foregroundColor: Colors.outColor,
        habitImage: require('../../assets/images/OutsideImage.png'),
        plantImage: require('../../assets/images/planet.png'),
        flowerImage: require('../../assets/images/flower-pot 1.png'),
        exportImage: require('../../assets/images/Export%.png'),
        backImage: require('../../assets/background/green.png'),
        backImageSize: { width: 120.41, height: 121.97 },
        cardColor: Colors.outGreen,
        buttonText: "Adventure",
        buttonColor: Colors.textAdventure,
    },
    {
        id: 4,
        title: "Morning exercise",
        content: "Morning exercise",
        time: "6:00 am - 6:00 pm",
        foregroundColor: Colors.exerciseColor,
        habitImage: require('../../assets/images/exercise.png'),
        plantImage: require('../../assets/images/planet.png'),
        flowerImage: require('../../assets/images/flower-pot 1.png'),
        exportImage: require('../../assets/images/Export%.png'),
        backImage: require('../../assets/background/pink.png'),
        backImageSize: { width: 79.37, height: 77.05 },
        cardColor: Colors.exercisePink,
        buttonText: "Meditation",
        buttonColor: Colors.textMeditation,
    },
];

export default Data;
